// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var ReBemHelper = require("../src/ReBemHelper.js");

var myActiveBemClassNames = ReBemHelper.bem(/* Some */["my-block"], /* None */0, /* Some */[/* :: */[
        /* Boolean */Block.__(1, [
            "active",
            /* true */1
          ]),
        /* [] */0
      ]], /* () */0);

ReBemHelper.bem(/* Some */["my-block"], /* None */0, /* Some */[/* :: */[
        /* String */Block.__(0, ["small"]),
        /* [] */0
      ]], /* () */0);

ReBemHelper.bem(/* Some */["my-block"], /* None */0, /* Some */[/* :: */[
        /* String */Block.__(0, ["small"]),
        /* :: */[
          /* Boolean */Block.__(1, [
              "active",
              /* true */1
            ]),
          /* [] */0
        ]
      ]], /* () */0);

var mySizeBemClassNames = ReBemHelper.bem(/* Some */["my-block"], /* Some */["element"], /* Some */[/* :: */[
        /* String */Block.__(0, ["small"]),
        /* [] */0
      ]], /* () */0);

var isActive = /* true */1;

exports.isActive = isActive;
exports.myActiveBemClassNames = myActiveBemClassNames;
exports.mySizeBemClassNames = mySizeBemClassNames;
/* myActiveBemClassNames Not a pure module */
