// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function join(separator, strings) {
  var _acc = "";
  var _strings = strings;
  while(true) {
    var strings$1 = _strings;
    var acc = _acc;
    if (strings$1) {
      var xs = strings$1[1];
      var x = strings$1[0];
      if (xs) {
        if (List.hd(xs) !== "") {
          _strings = xs;
          _acc = acc + (x + separator);
          continue ;
          
        } else if (List.hd(xs) === "") {
          _strings = xs;
          _acc = acc + x;
          continue ;
          
        } else {
          throw [
                Caml_builtin_exceptions.match_failure,
                [
                  "BemHelper.re",
                  9,
                  4
                ]
              ];
        }
      } else {
        return acc + x;
      }
    } else {
      return acc;
    }
  };
}

function getModifierClassNames(modifiers, base) {
  return List.map((function (item) {
                if (item.tag) {
                  if (item[1] !== 0) {
                    return base + ("--" + item[0]);
                  } else {
                    return "";
                  }
                } else {
                  return base + ("--" + item[0]);
                }
              }), modifiers);
}

function bem(block, element, modifiers, _) {
  var classNames;
  if (block) {
    var block$prime = block[0];
    if (element) {
      var element$prime = element[0];
      if (modifiers) {
        var className = block$prime + ("__" + element$prime);
        classNames = List.append(/* :: */[
              className,
              /* [] */0
            ], getModifierClassNames(modifiers[0], className));
      } else {
        classNames = /* :: */[
          block$prime + ("__" + element$prime),
          /* [] */0
        ];
      }
    } else {
      classNames = modifiers ? List.append(/* :: */[
              block$prime,
              /* [] */0
            ], getModifierClassNames(modifiers[0], block$prime)) : /* :: */[
          block$prime,
          /* [] */0
        ];
    }
  } else if (element) {
    var element$prime$1 = element[0];
    classNames = modifiers ? List.append(/* :: */[
            element$prime$1,
            /* [] */0
          ], getModifierClassNames(modifiers[0], element$prime$1)) : /* :: */[
        element$prime$1,
        /* [] */0
      ];
  } else {
    classNames = /* [] */0;
  }
  return join(" ", classNames);
}

var $$default = bem;

exports.join = join;
exports.getModifierClassNames = getModifierClassNames;
exports.bem = bem;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* No side effect */
